remove jekyll-redirect-from gem
Was breaking the build...

```
Error: Yikes! It looks like you don't have jekyll-redirect-from or one
of its dependencies installed. In order to use Jekyll as currently
configured, you'll need to install this gem.
```